import type { Metadata } from "next";
import { Fira_Mono, Inter } from "next/font/google";
import "../../public/globals.css";
import { Providers } from "./Providers";
import { Toaster } from "@/components/ui/toaster"

const inter = Fira_Mono({ subsets: ["cyrillic", "latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
